@startuml name
(*) -->"
{{
    salt
    {
        <b>ソウルライブバンド管理アプリ
        ライブ|出演バンド表示
        soul live vol.12 A|[選択]
        soul live vol.12 B|[選択]
        soul live vol.12 C|[選択]
        soul live vol.12 final|[選択]
        soulmates × HomeGround合同ライブ|[選択]
        [ライブメンテナンス]
        [メンバーメンテナンス]
    }
}}
" as home

home -down->"
{{
    salt
    {
        <b>出演バンド
        soul live vol.12 A
        出演順|バンドID|バンド名|メンバー|スケジュール|""|""
        1|B001|「お、今度の飯はししゃもか、母さん」|かとまり 荒井 のぶ 三上|11:50~12:20|[削除]|[変更]|[メンバー追加]
        2|B002|麦南|サカタニ のぶ たなしゅん おか めぐ りょう|12:20~12:45|[削除]|[変更]|[メンバー追加]
        [出演バンド追加][戻る]
    }
}}
" as show_band

show_band -down->"
{{
    salt
    {
        <b>出演バンド追加
        soul live vol.12 A 日程
        バンドID|"B003"
        バンド名|"インストもん"
        出演順|"3"
        出演時間|"12:50~13:20"
        [追加][戻る]
    }
}}
" as insert_band_for_live

show_band -left->"
{{
    salt
    {
        <b>バンド登録情報変更
        soul live vol.12 A 日程
        バンド名|"インスト侍"
        出演順|"3"
        出演時間|"12:50~13:20"
        [追加][戻る]
    }
}}
" as update_band_for_live

show_band -right->"
{{
    salt
    {
        <b>バンド メンバー追加
        メンバーID|"2019001"
        [追加][戻る]
    }
}}
" as formation_member

home -right->"
{{
    salt
    {
        ソウルライブバンド管理アプリ
        <b>ライブ メンテナンス
        ライブ名|""
        soul live vol.12 A|[削除]
        soul live vol.12 B|[削除]
        soul live vol.12 C|[削除]
        soul live vol.12 final|[削除]
        soulmates×HomeGround合同ライブ|[削除]
        [ライブ追加]
        [戻る]
    }
}}
" as live_mentenance

live_mentenance ->"
{{
    salt
    {
        <b>ライブ追加
        ライブ名|"soul live vol.13 A"
        ライブID|"201901A"
        [追加][戻る]
    }
}}
" as insert_live

home -left->"
{{
    salt
    {
        <b>メンバーメンテナンス
        メンバーID|名前|""
        2019001|かとまり|[削除]
        2019002|荒井|[削除]
        2019003|のぶ|[削除]
        [メンバー追加][戻る]
    }
}}
" as mentenance_member

mentenance_member -left->"
{{
    salt
    {
        <b>メンバー追加
        メンバーID|"20190004"
        名前|"三上"
        [追加][戻る]
    }
}}
" as insert_member

@enduml